// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCel1jqPzTAw7vainc14AVsss60Nr3L0vs',
    appId: '1:652933893336:web:af65b800fb9cb165bf1bad',
    messagingSenderId: '652933893336',
    projectId: 'first-3a697',
    authDomain: 'first-3a697.firebaseapp.com',
    storageBucket: 'first-3a697.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4hZdQqDD_7lSDyhSdfgEk0EYGmqVWz9w',
    appId: '1:652933893336:android:0c9abc3500e6d596bf1bad',
    messagingSenderId: '652933893336',
    projectId: 'first-3a697',
    storageBucket: 'first-3a697.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA32O3P36aIyFhP6DGNubpOfSEIO8CnVws',
    appId: '1:652933893336:ios:aa52e9a529221126bf1bad',
    messagingSenderId: '652933893336',
    projectId: 'first-3a697',
    storageBucket: 'first-3a697.appspot.com',
    iosBundleId: 'com.example.firebaseBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA32O3P36aIyFhP6DGNubpOfSEIO8CnVws',
    appId: '1:652933893336:ios:eeb576606a29b8c4bf1bad',
    messagingSenderId: '652933893336',
    projectId: 'first-3a697',
    storageBucket: 'first-3a697.appspot.com',
    iosBundleId: 'com.example.firebaseBase.RunnerTests',
  );
}
